services:
    liipto.default.controller:
        class: Application\LiipToBundle\Controller\DefaultController
        arguments:
            - @view

    liipto.apicalls.controller:
        class: Application\LiipToBundle\Controller\ApiCallsController
        arguments:
            - @view
            - @request
            - @database_connection
            - @router
            - @response
#        calls:
#            - [setContainer, [@service_container]]


