root:
    pattern:  /
#    defaults: { _controller: LiipToBundle:Default:index }
    defaults: { _controller: liipto.default.controller:indexAction }
redirect:
    pattern: /{url}
    defaults: { _controller: liipto.apicalls.controller:redirectAction }
api.rchkrev:
    pattern: /api/rchkrev/
    defaults: { _controller: liipto.apicalls.controller:checkCodeReverseAndRevCanAction, _format: json }
api.txt:
    pattern: /api/txt/
    defaults: { _controller: liipto.apicalls.controller:createAction, _format: json }
